### PR TITLE
[xaudio2] Rewrite to use FAudio, add xactengine support

### PR DESCRIPTION
**Pull request by flibitijibibo**
This is the FAudio rewrite rebased against WineHQ master. It is not intended to be the "official" pull request, but rather a quick way to look at the changes against upstream.

### CODE REVIEW

**Comment by aeikum** [comment]
Thanks, overall this looks pretty good. I'm going to get it building on my end and play with it a bit.

One general comment is we'll want to split the xactengine stuff into a separate commit from the FAudio conversion.

We're also going to need to figure out where the tests will live and how to run them. [vkd3d](https://source.winehq.org/git/vkd3d.git/) may provide an example. The d3d12 tests live in their source tree, and they provide the ability to invoke mingw compilers to build the Windows binaries that run the tests on Windows. So we could follow that example and move Wine's xaudio2 tests into FAudio. Then changes to FAudio should also add tests.

**Comment by flibitijibibo** [comment]
Will separate the XACT stuff when the next change happens. I pushed a tiny update that fixes the FAudio detection, so ./configure should now build the DLLs when FAudio is found.

**Comment by flibitijibibo** [comment]
Patch has been updated to include the changes from faudio-fixups and separates the XACT work into a separate commit.

**Comment by flibitijibibo** [comment]
Updated to resolve the conflict from yesterday's xaudio_dll.c update.

**Comment by flibitijibibo** [comment]
Updated for latest master and includes the %esi corruption fix, which also applies to this rewrite.

**Comment by kakurasan** [comment]
I tested this branch (e1e1969 + FNA-XNA/FAudio@27cdf05, 32-bit) but it's buggy for me.

I wrote [a test program](https://github.com/flibitijibibo/wine/files/2557560/dxlib-playsoundfile-test.tar.gz) (simple player that uses [DX Library](http://dxlib.o.oo7.jp/)) but it doesn't play MP3 files via `l3codeca.acm.so` properly. Wine's old implementation works.

**Comment by flibitijibibo** [comment]
Have any information to go with that? This test program is extremely large, so I have no idea what is being used when, with what data, etc.

Trim this down to the bare XAudio2 API calls and that will be easier to debug, without that you'd have a much better time debugging this than me since you know the whole program more intimately. You most likely care about FAudio_INTERNAL_MixSource and FAudio_INTERNAL_MixSubmix, which can be found in `src/FAudio_internal.c`.

**Comment by aeikum** [comment]
Hey @kakurasan. I'm able to play MP3 files with FNA-XNA/FAudio@048c79fd81. The audio does skip around a bit. Is that the problem you are seeing? I also hear some skips with Wine's current xaudio2 implementation, but it is less noticeable.

**Comment by flibitijibibo** [comment]
The latest FAudio commits may possibly deal with this; a recent change for FFmpeg support broke decoding in a way that would introduce uninitialized data at the ends of buffers, introducing gaps or chirps between blocks.

**Comment by flibitijibibo** [comment]
This is totally a guess, but looking at the lib's callback implementation I'm guessing the skip is due to OnVoiceProcessingPassStart being used, and our BytesRequired value is inaccurate. It seems to _really_ depend on the value being exactly correct, or else it will overwrite its own data and cause the skips you're hearing. So, for example, with a 1024-sample update:

1. Source starts, sends 1536 samples of float32 data (6144 bytes)
2. Audio engine does a pass, BytesRequired is 0, takes in 1024 samples
3. Audio engine does a second pass, BytesRequired is now 2048 because it needs 512 more samples

This is harder than it sounds because we need to have very specific information from the whole buffer queue; for example, you could have buffer 1 with 128 samples, buffer 2 with 512 samples, and buffer 3 with 256 samples, and the engine will need to be able to tell the callback that it needs 512 bytes for the last 128 samples in the update.

I _think_ I got this, but I wasn't able to test specifically with this program:

https://github.com/FNA-XNA/FAudio/commit/1233ea596613f63dc5a24c69757b02c7a6ccd890

**Comment by flibitijibibo** [comment]
Writing this down for myself: Had to fix some BOOL size stuff, thankfully Wine is unaffected except for GetEffectState, which should use `int32_t result` instead of `uint8_t`:

https://github.com/FNA-XNA/FAudio/commit/8629fc2a39d25c1741c71547e0ec08daa32fd647

Will update this when I'm back at my main setup...

**Comment by kakurasan** [comment]
Thanks, the skipping issue is fixed for me too (e1e1969 with [BOOL size patch](#issuecomment-437537624) + FNA-XNA/FAudio@8c2ef08).

**Comment by flibitijibibo** [comment]
Updated for EngineProcedureEXT.

**Comment by flibitijibibo** [comment]
Updated with Andrew's threading fixes and other minor cleanup that was needed after the last force push.

**Comment by flibitijibibo** [comment]
Rebased against 3.21 and changed the X3DAudio/XAPOFX DLLs to prefer builtin instead of native.

**Comment by ahmed-elsayed2017** [comment]
Is Esync included in this branch?

**Comment by flibitijibibo** [comment]
No, this is stock 3.21 with the audio patches applied. No extra changes are in this changeset.

**Comment by flibitijibibo** [comment]
Latest push is pretty much the same, just fixes the XACT CLSIDs.

**Comment by flibitijibibo** [comment]
One more push with a couple fixes to get Megadimension Neptunia VIIR booting again...

**Comment by flibitijibibo** [comment]
Even moar Neptunia fixes today. Now streaming WaveBanks work!

**Comment by flibitijibibo** [comment]
Pushed a rather interesting change... I've separated CreateMasteringVoice based on the XAudio2 versions, since <=7 has a different API than >=8:

https://github.com/flibitijibibo/wine/commit/bcac3b465e9e4a3a26397fab0673fda64ddd9113

**Comment by flibitijibibo** [comment]
One more to remove the `__APPLE__` defs... I dunno if we can actually use pthread but the previous patch didn't def everything out for macOS anyway, so for now let's get it to compile and the right people will slap me on the wrist if we can't use it.

**Comment by flibitijibibo** [comment]
Rebased against Wine 4.0!

**Comment by flibitijibibo** [comment]
One more push to remove the tests - somehow I never thought to do that after we migrated them to the FAudio repository.

**Comment by flibitijibibo** [comment]
Rebased against Wine 4.1.

**Comment by flibitijibibo** [comment]
One quick push for some patch feedback, primarily reintroduces test files for stuff that's specific to Wine (QueryInterface, XAPO creation, etc).

**Comment by flibitijibibo** [comment]
Latest push is the exact set of commits that were just sent to the wine-devel mailing list for consideration in upstream...

**Comment by flibitijibibo** [comment]
Looks like both patches got blown apart. The latest push undoes the XAudio2 test deletion (even though it's all a dupe of the FAudio tests), there will probably be one more push later with a new patch that adds a whole bunch of tests for the XAudio2 headers.

**Comment by flibitijibibo** [comment]
This pull request is now partially redundant, as the FAudio rewrite is now in 4.3!

https://www.winehq.org/announce/4.3

Will make a separate PR to visualize the XACT work as that develops.

**Pull request closed without merging**
